// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8VeVQFBaEL00x3BlKJwyvUfgWVJ1LM6c',
    appId: '1:593380974598:web:cd947ae0c045261fc3a387',
    messagingSenderId: '593380974598',
    projectId: 'test-app-a9a73',
    authDomain: 'test-app-a9a73.firebaseapp.com',
    databaseURL: 'https://test-app-a9a73-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-a9a73.appspot.com',
    measurementId: 'G-XXMC7CYHTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcqarFenTySpHQJ_enPPhQk3VBRlcdSvo',
    appId: '1:593380974598:android:056fcec699fd583ec3a387',
    messagingSenderId: '593380974598',
    projectId: 'test-app-a9a73',
    databaseURL: 'https://test-app-a9a73-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-a9a73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcFqLFo2EOQ3xejl1VJLABg8lK2J37anI',
    appId: '1:593380974598:ios:ab0efa64f054d861c3a387',
    messagingSenderId: '593380974598',
    projectId: 'test-app-a9a73',
    databaseURL: 'https://test-app-a9a73-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-a9a73.appspot.com',
    iosClientId: '593380974598-fqgkl39m52tomrep1vpjvcpk3chnn2o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthorization',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcFqLFo2EOQ3xejl1VJLABg8lK2J37anI',
    appId: '1:593380974598:ios:cb9b8653c2ae19b4c3a387',
    messagingSenderId: '593380974598',
    projectId: 'test-app-a9a73',
    databaseURL: 'https://test-app-a9a73-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-a9a73.appspot.com',
    iosClientId: '593380974598-pavhm1btsnsu1sihsotkjkmid2i79mac.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthorization.RunnerTests',
  );
}
